In [1]:
import numpy as np
import pandas as pd

Завдання до лабораторної роботи
Створити програму, яка:
1. Генерує випадкові масиви різними способами, зазначеними в
теоретичних відомостях.
2. Демонструє звернення до елементів масиву за допомогою індексів, в
тому числі від’ємних; виділення підмасивів.
3. Демонструє основні арифметичні операції над масивами, а також роботу
методів reduce ,  accumulate, outer.
4. Вираховує  статистичні  характеристики,  а  саме,  мінімальне  і
максимальне  значення,  вибіркові  середнє,  дисперсію,
середньоквадратичне відхилення, медіану та 25 та 75 персентилі,
величини ширина пелюстки (petal_width) з набору даних щодо квіток
ірису (iris.csv).

Генерує випадкові масиви різними способами, зазначеними в теоретичних відомостях.

In [2]:
random_generator = np.random.default_rng()
random_values = random_generator.normal(10, 1, (3, 3))
print(random_values)
another_random_values = np.random.normal(10, 2, (3, 3))
print(another_random_values)
one_more_random_values = np.random.randint(8, 11, (3, 3))
print(one_more_random_values)
last_random_values = np.random.random((3, 3))
print(last_random_values)

[[10.33343029 10.23550808 11.91659716]
 [ 9.43783831  9.38852152 11.4815357 ]
 [ 9.79835156  9.02900832  9.23521865]]
[[ 9.80567144  8.10928758  7.79850445]
 [ 9.80584238  9.91331023 11.92263236]
 [10.87567938 11.89442429 11.86403434]]
[[10 10 10]
 [ 9  9 10]
 [ 9  8  9]]
[[0.83338046 0.22527493 0.87158805]
 [0.42966354 0.16749947 0.01707719]
 [0.17624723 0.52690629 0.96962163]]


Демонструє звернення до елементів масиву за допомогою індексів, в тому числі від’ємних; виділення підмасивів.

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a[0])  # first array
print(a[0][1])  # second element from first array
print(a[-2][-2])  # second element from the end from the second from the end array
print(a[1, -2])  # second element from the end from the second array
print(a[::2])  # two-dimensional array that include all arrays from first to last with step equal 2
print(a[1::-1])  # two-dimensional array that include all arrays from second to first with step equal 1

[1 2 3]
2
5
5
[[1 2 3]
 [7 8 9]]
[[4 5 6]
 [1 2 3]]


Демонструє основні арифметичні операції над масивами, а також роботу методів reduce , accumulate, outer.

In [4]:
ones=np.ones(4)
ones+18, ones*32, (ones+1)**(1/2), a/2, -a, np.sin(ones/2)

(array([19., 19., 19., 19.]),
 array([32., 32., 32., 32.]),
 array([1.41421356, 1.41421356, 1.41421356, 1.41421356]),
 array([[0.5, 1. , 1.5],
        [2. , 2.5, 3. ],
        [3.5, 4. , 4.5]]),
 array([[-1, -2, -3],
        [-4, -5, -6],
        [-7, -8, -9]]),
 array([0.47942554, 0.47942554, 0.47942554, 0.47942554]))

In [5]:
ones*2 + ones*3, (ones*2) * (ones * 3)

(array([5., 5., 5., 5.]), array([6., 6., 6., 6.]))

In [6]:
arr =np.array([[1,2,3],[4,5,6],[7,8,9]])
arr, np.multiply.reduce(arr), np.multiply.reduce(arr, axis=1)

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 array([ 28,  80, 162]),
 array([  6, 120, 504]))

In [7]:
np.multiply.accumulate(arr)

array([[  1,   2,   3],
       [  4,  10,  18],
       [ 28,  80, 162]], dtype=int32)

In [8]:
a = np.array([1,2,3,4,5,6,7,8,9])
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
np.add.outer(ar, a)

array([[[ 2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 3,  4,  5,  6,  7,  8,  9, 10, 11],
        [ 4,  5,  6,  7,  8,  9, 10, 11, 12]],

       [[ 5,  6,  7,  8,  9, 10, 11, 12, 13],
        [ 6,  7,  8,  9, 10, 11, 12, 13, 14],
        [ 7,  8,  9, 10, 11, 12, 13, 14, 15]],

       [[ 8,  9, 10, 11, 12, 13, 14, 15, 16],
        [ 9, 10, 11, 12, 13, 14, 15, 16, 17],
        [10, 11, 12, 13, 14, 15, 16, 17, 18]]])

In [12]:
data = pd.read_csv('iris.csv')
petalWd = np.array(data['petal_width'])

Вираховує статистичні характеристики, а саме, мінімальне і максимальне значення, вибіркові середнє, дисперсію, середньоквадратичне відхилення, медіану та 25 та 75 персентилі, величини ширина пелюстки (petal_width) з набору даних щодо квіток ірису (iris.csv).

In [13]:
np.multiply.accumulate(ar)

array([[  1,   2,   3],
       [  4,  10,  18],
       [ 28,  80, 162]], dtype=int32)

In [14]:
petalWd.max()

2.5

In [15]:
petalWd.min()

0.1

In [16]:
petalWd.mean()

1.1986666666666668

In [17]:
petalWd.var(ddof=1)

0.582414317673378

In [18]:
petalWd.std(ddof=1)

0.7631607417008411

In [19]:
np.percentile(petalWd,25)

0.3

In [20]:
np.median(petalWd)

1.3

In [21]:
np.percentile(petalWd,75)

1.8